config/routes.rb
Gaming::Application.routes.draw do

  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  mount Refinery::Core::Engine, :at => '/b'

  root :to => 'home#index'

  match '/p/about' => 'home#about', :as => :about

  match '/b' => 'home#refinery_logout'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/p/signout' => 'sessions#destroy', :as => :signout
  match '/p/signin' => 'sessions#new', :as => :signin_facebook
  match '/p/signin_twitch' => 'sessions#new_twitch', :as => :signin_twitch

  get '/p/users' => 'users#index', :as => :users

  get ':name' => 'streams#show', :as => :stream_show
  get '/p/streams' => 'streams#index', :as => :streams
  get '/stream/:id/new' => 'streams#new', :as => :new_stream
  post '/stream/:id/new' => 'streams#create', :as => :stream
  get '/stream/:id/edit' => 'streams#edit', :as => :edit_stream
  put '/stream/:id' => 'streams#update'
  get '/p/featured_streams' => 'streams#featured_index', :as => :featured_streams

  get '/p/videos' => 'videos#index', :as => :videos
  get '/video/:id' => 'videos#show', :as => :show_video

  match '/p/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/p/contact' => 'contact#create', :as => 'contact', :via => :post

end

app/models/stream.rb
class Stream < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  def show
    @stream_name = params[:name]
    @stream_data = get_twitch_stream(params[:name])
    redirect_to streams_path, :notice => "the user is not online" if @stream_data.nil?
  end

  def index
    @streams = Stream.all
    @list_of_streams = @streams.reduce("") do |stream_list, stream|
      (stream_list << ("#{stream.name},").gsub(/\s+/, ""))
    end

    @online_streams = get_stream_list(@list_of_streams)
    redirect_to featured_streams_path if @online_streams.empty?
  end

  def featured_index
    @featured_streams = get_featured_streams
  end

  def show_featured
    @stream_name = params[:name]
    @stream_data = (JSON.parse(RestClient.get "https://api.twitch.tv/kraken/streams/#{params[:name].gsub(/\s+/, "")}"))["stream"]
  end

  def new
    @stream = Stream.new(params[:user])
  end

  def create
    @user = User.find_by_id(params[:id])
    @stream = Stream.new(name: (params[:stream][:name]).downcase.gsub(/\s+/, ""), user_id: @user.id)
    if @stream.save
      flash[:success] = "stream added to #{@user.name}"
      redirect_to users_path
    else
      render :action => "new"
    end
  end

  def edit
    @stream = Stream.find_by_id(params[:id])
  end

  def update
    @stream = Stream.find_by_id(params[:id])
    @stream.update_attributes(params[:stream])
    redirect_to users_path
  end
end

app/views/streams/edit.html.haml
.container
  = form_for @stream, :url => stream_show_path(@stream.id) do |f|
    %p current stream name
    %div= @stream.user.name
    %div= @stream.name
    %br/
    %div= f.label "Stream Name"
    %div= f.text_field "name"
    %input.btn.btn-primary{:type => "submit"}

app/views/streams/featured_index.html.haml
.container.stream-list
  .row-fluid.stream-row
    .span12.stream-row
      .alert.alert-error
        %h4 looks like no chicago streamers at the moment, while you're here why not checkout the featured streams of Twitch.
      - @featured_streams.each do |stream|
        .span4.stream-layout
          .title
            %h5
              = truncate(stream["stream"]["channel"]["status"], :length => 40)
          .show-stream
            %a{:href => stream_show_path(stream["stream"]["channel"]["name"])}
            %img.stream-img{:src => stream["stream"]["preview"]["medium"]}
            .stream-content
              = link_to stream["stream"]["channel"]["display_name"], stream_show_path(stream["stream"]["channel"]["name"]), :class => "stream-link"
              with
              = stream["stream"]["viewers"]
              viewers
              %br/
              playing
              = stream["stream"]["game"]

app/views/streams/index.html.haml
.container.stream-list
  .row-fluid.stream-row
    .span12.stream-row
      - if !@online_streams.empty?
        - @online_streams.each do |stream|
          - @stream_user = Stream.where(name: stream["channel"]["url"].split('/')[3])
          .span4.stream-layout
            .title
              %h5
                = truncate(stream["channel"]["status"], :length => 40)
            .show-stream
              %a{:href => stream_show_path(@stream_user[0].name)}
                %img.stream-img{:src => stream["preview"]["medium"]}
              .stream-content
                = link_to @stream_user[0].user.name, stream_show_path(@stream_user[0].name), :class => "stream-link"
                (
                = stream["channel"]["display_name"]
                )
                with
                = stream["viewers"]
                viewers
                %br/
                playing
                = stream["game"]

app/views/streams/new.html.haml
.container
  = form_for @stream, :url => new_stream_path do |form|
    %fieldset.fields
      .field
        = form.label "Twitch Account Name"
        = form.text_field :name
    %fieldset.actions
      = form.submit "Add"

  - if flash[:success]
    .alert.alert-success
      = flash[:succes]

app/views/streams/show.html.haml
.container-fluid.stream-show
  .row-fluid
    .span9.stream-show
      %h4
        = @stream_data["channel"]["status"]
        %small
          = @stream_data["channel"]["display_name"]
          playing
          = @stream_data["game"]
      %object#live_embed_player_flash{:bgcolor => "#000000",
        :data => "http://www.twitch.tv/widgets/live_embed_player.swf?channel=#{@stream_name}",
        :height => "100%",
        :width => "100%",
        :type => "application/x-shockwave-flash"}
        %param{:name => "allowFullScreen", :value => "true"}/
        %param{:name => "allowScriptAccess", :value => "always"}/
        %param{:name => "allowNetworking", :value => "all"}/
        %param{:name => "movie", :value => "http://www.twitch.tv/widgets/live_embed_player.swf"}/
        %param{:name => "flashvars", :value => "hostname=www.twitch.tv&channel=#{@stream_name}&auto_play=true&start_volume={VOLUME}"}/

    .span3.stream-chat
      %iframe#chat_embed{:frameborder => "0",
        :height => "645px",
        :scrolling => "no",
        :src => "http://twitch.tv/chat/embed?channel=#{@stream_name}&amp;popout_chat=true",
        :width => "300px"}

app/views/streams/show_featured.html.haml
.container
.container-fluid.stream-show
  .row-fluid
    .span9.stream-show
      %h4
        = @stream_data["channel"]["status"]
        %small
          = @stream_data["channel"]["display_name"]
          playing
          = @stream_data["game"]
      %object#live_embed_player_flash{:bgcolor => "#000000",
        :data => "http://www.twitch.tv/widgets/live_embed_player.swf?channel=#{@stream_name}",
        :height => "100%",
        :width => "100%",
        :type => "application/x-shockwave-flash"}
        %param{:name => "allowFullScreen", :value => "true"}/
        %param{:name => "allowScriptAccess", :value => "always"}/
        %param{:name => "allowNetworking", :value => "all"}/
        %param{:name => "movie", :value => "http://www.twitch.tv/widgets/live_embed_player.swf"}/
        %param{:name => "flashvars", :value => "hostname=www.twitch.tv&channel=#{@stream_name}&auto_play=true&start_volume={VOLUME}"}/

    .span3.stream-chat
      %iframe#chat_embed{:frameborder => "0",
        :height => "645px",
        :scrolling => "no",
        :src => "http://twitch.tv/chat/embed?channel=#{@stream_name}&amp;popout_chat=true",
        :width => "300px"}