config/routes.rb
Gaming::Application.routes.draw do

  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"
  mount Refinery::Core::Engine, :at => '/b'

  root :to => 'home#index'

  match '/p/about' => 'home#about', :as => :about

  match '/b' => 'home#refinery_logout'

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'
  match '/p/signout' => 'sessions#destroy', :as => :signout
  match '/p/signin' => 'sessions#new', :as => :signin_facebook
  match '/p/signin_twitch' => 'sessions#new_twitch', :as => :signin_twitch

  get '/p/users' => 'users#index', :as => :users

  get ':name' => 'streams#show', :as => :stream_show
  get '/p/streams' => 'streams#index', :as => :streams
  get '/stream/:id/new' => 'streams#new', :as => :new_stream
  post '/stream/:id/new' => 'streams#create', :as => :stream
  get '/stream/:id/edit' => 'streams#edit', :as => :edit_stream
  put '/stream/:id' => 'streams#update'
  get '/p/featured_streams' => 'streams#featured_index', :as => :featured_streams

  get '/p/videos' => 'videos#index', :as => :videos
  get '/video/:id' => 'videos#show', :as => :show_video

  match '/p/contact' => 'contact#new', :as => 'contact', :via => :get
  match '/p/contact' => 'contact#create', :as => 'contact', :via => :post

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @yt_videos = yt_client.my_videos.videos
  end

  def show
    @yt_video = yt_client.video_by(params[:id])
  end
end

app/views/videos/index.html.haml
.container
  .row-fluid.videos-list
    .span12
      .row-fluid
        .title
          %h3 kennyTERROR Videos
          %a{:href => "#", :onclick => "$('#hidden').show(); return false;"}
            show
          %a{:href => "#", :onclick => "$('#hidden').hide(); return false;"}
            hide
          %div#hidden{:style => "display: none;"}
            - @yt_videos.each do |video|
              %ul{:style => "list-style-type: none;"}
                %li
                  = link_to video.title.split("kennyTERROR")[0], show_video_path(video.unique_id), :class => "video-link"
                  = video.view_count
                  views

app/views/videos/show.html.haml
.container
  .row-fluid
    .span12.video-show
      %h2= @yt_video.title
      = raw @yt_video.embed_html5({:class => 'video-player', :id => 'my-video', :width => "100%", :height => "600", :frameborder => '1', :url_params => {:option_one => "value", :option_two => "value"}})

      .span8.video-detail
        %h5
          = @yt_video.view_count
          views
          %br/
          = @yt_video.description
      .span4.subscribe
        %iframe{:scrolling => "no", :src => "http://www.youtube.com/subscribe_widget?p=#{@yt_video.author.name}", :style => "overflow: hidden; height: 105px; width: 375px; border: none;"}



      #disqus_thread
        :javascript
          var disqus_shortname = 'terrorgaming';

          (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);})();
        %noscript
          Please enable JavaScript to view the
          %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.
          %a.dsq-brlink{:href => "http://disqus.com"}
          comments powered by
          %span.logo-disqus Disqus